{
  "hash": "bb1f5c6f8b289ca991c3f6010b61d4b0",
  "result": {
    "markdown": "---\ntitle: \"Les éditions olympiques\"\nauthor: \"Emma Labre Blanc\"\ndate: \"2024-02-28\"\ncategories: [news]\nimage: \"grece.jpg\"\n---\n\n\nDans cet article, nous vons proposons de découvrir le nombre d'éditions auxquelles chaque discipline a été présente et d'obtenir des informations sur l'attribution des médailles olympiques.\n\n## Les données utilisées\n\nLes données utilisées pour cet article sont issues du site web suivant : https://fr.wikipedia.org/wiki/Liste_des_m%C3%A9daill%C3%A9s_olympiques.\n\nDe plus, nous avons dû effectuer quelques modifications avant de pouvoir les analyser :\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importation des librairies\nlibrary(rvest)\nlibrary(purrr)\nlibrary(lubridate)\nlibrary(stringr)\nlibrary(tibble)\nlibrary(dplyr)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importation du jeu de données\nlist_tables <-\n  session(\"https://fr.wikipedia.org/wiki/Liste_des_m%C3%A9daill%C3%A9s_olympiques\") |>\n  html_elements(\".wikitable\") |>\n  html_table()\n\nlist_tables\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[1]]\n# A tibble: 31 × 11\n   Discipline   Discipline   Années `Nombre de` `Nombre de` `médailles décernés`\n   <chr>        <chr>        <chr>  <chr>       <chr>       <chr>               \n 1 \"Discipline\" Discipline   Années Éditions    Épreuves(e… Or                  \n 2 \"\"           Athlétisme   Depui… 29          48          1028                \n 3 \"\"           Aviron       Depui… 28          14          269                 \n 4 \"\"           Badminton    Depui… 8           5           39                  \n 5 \"\"           Basket-ball  Depui… 20          4           32                  \n 6 \"\"           Boxe         1904,… 26          13          266                 \n 7 \"\"           Canoë-kayak  Depui… 20          16          242                 \n 8 \"\"           Cyclisme(ho… Depui… 29          22          263                 \n 9 \"\"           Équitation   1900,… 26          6           151                 \n10 \"\"           Escrime      Depui… 29          12          223                 \n# ℹ 21 more rows\n# ℹ 5 more variables: `médailles décernés` <chr>, `médailles décernés` <chr>,\n#   `médailles décernés` <chr>,\n#   `Athlète(s) avec le plus de médailles (Or-Argent-Bronze)` <chr>,\n#   `Athlète(s) avec le plus de médailles d'or` <chr>\n\n[[2]]\n# A tibble: 16 × 11\n   Discipline   Discipline   Années `Nombre de` `Nombre de` `médailles décernés`\n   <chr>        <chr>        <chr>  <chr>       <chr>       <chr>               \n 1 \"Discipline\" Discipline   Années Éditions    épreuves e… Or                  \n 2 \"\"           Biathlon     1924,… 16          11          54                  \n 3 \"\"           Bobsleigh    1924-… 21          3           39                  \n 4 \"\"           Combiné nor… Depui… 22          3           28                  \n 5 \"\"           Curling      1924,… 4           2           7                   \n 6 \"\"           Hockey sur … Été :… 23          2           24                  \n 7 \"\"           Luge         Depui… 14          4           37                  \n 8 \"\"           Patinage ar… Été :… 24          4           77                  \n 9 \"\"           Patinage de… Depui… 22          12          152                 \n10 \"\"           Patinage de… Depui… 7           8           32                  \n11 \"\"           Saut à ski   Depui… 22          4           38                  \n12 \"\"           Skeleton     1924,… 6           2           6                   \n13 \"\"           Ski acrobat… Depui… 7           10          18                  \n14 \"\"           Ski alpin    Depui… 19          10          132                 \n15 \"\"           Ski de fond  Depui… 22          12          134                 \n16 \"\"           Snowboard    Depui… 5           10          14                  \n# ℹ 5 more variables: `médailles décernés` <chr>, `médailles décernés` <chr>,\n#   `médailles décernés` <chr>,\n#   `Athlète(s) avec le plus de médailles (Or-Argent-Bronze)` <chr>,\n#   `Athlète(s) avec le plus de médailles d'or` <chr>\n\n[[3]]\n# A tibble: 14 × 8\n   Discipline   Discipline       Années `Nombre d'éditions` `Médailles décernés`\n   <chr>        <chr>            <chr>  <chr>               <chr>               \n 1 \"Discipline\" Discipline       Années Nombre d'éditions   Or                  \n 2 \"\"           Baseball         1992–… 5                   5                   \n 3 \"\"           Pelote basque    1900   1                   1                   \n 4 \"\"           Cricket          1900   1                   1                   \n 5 \"\"           Croquet          1900   1                   3                   \n 6 \"\"           Jeu de paume     1908   1                   1                   \n 7 \"\"           Crosse           1904–… 2                   2                   \n 8 \"\"           Polo             1900,… 5                   5                   \n 9 \"\"           Jeu de raquettes 1908   1                   2                   \n10 \"\"           Roque            1904   1                   1                   \n11 \"\"           Rugby à XV       1900,… 4                   4                   \n12 \"\"           Softball         1996–… 4                   4                   \n13 \"\"           Tir à la corde   1900–… 5                   5                   \n14 \"\"           Motonautisme     1908   5                   3                   \n# ℹ 3 more variables: `Médailles décernés` <chr>, `Médailles décernés` <chr>,\n#   `Médailles décernés` <chr>\n\n[[4]]\n# A tibble: 2 × 8\n  Discipline   Discipline        Années `Nombre d'éditions` `Médailles décernés`\n  <chr>        <chr>             <chr>  <chr>               <chr>               \n1 \"Discipline\" Discipline        Années Nombre d'éditions   Or                  \n2 \"\"           Patrouille milit… 1924   1                   1                   \n# ℹ 3 more variables: `Médailles décernés` <chr>, `Médailles décernés` <chr>,\n#   `Médailles décernés` <chr>\n\n[[5]]\n# A tibble: 30 × 11\n   Jeux  Médaille  Médaille Hôte     Nombred'épreuves(ave…¹ `Médailles décernés`\n   <chr> <chr>     <chr>    <chr>    <chr>                  <chr>               \n 1 Jeux  Médaille  Médaille Hôte     Nombred'épreuves(avec… Or                  \n 2 1896  médaillés tableau  Athènes… 43                     43                  \n 3 1900  médaillés tableau  Paris, … 95                     90                  \n 4 1904  médaillés tableau  Saint-L… 91                     96                  \n 5 1908  médaillés tableau  Londres… 110                    110                 \n 6 1912  médaillés tableau  Stockho… 102                    103                 \n 7 1920  médaillés tableau  Anvers,… 154                    156                 \n 8 1924  médaillés tableau  Paris, … 126                    126                 \n 9 1928  médaillés tableau  Amsterd… 109                    111                 \n10 1932  médaillés tableau  Los Ang… 117                    116                 \n# ℹ 20 more rows\n# ℹ abbreviated name: ¹​`Nombred'épreuves(avec médailles)`\n# ℹ 5 more variables: `Médailles décernés` <chr>, `Médailles décernés` <chr>,\n#   `Médailles décernés` <chr>,\n#   `Athlète(s) avec le plus de médailles (Or-Argent-Bronze)` <chr>,\n#   `Athlète(s) avec le plus de médailles d'or` <chr>\n\n[[6]]\n# A tibble: 24 × 11\n   Jeux  Médaille  Médaille Hôte     Nombred'épreuves(ave…¹ `Médailles décernés`\n   <chr> <chr>     <chr>    <chr>    <chr>                  <chr>               \n 1 Jeux  Médaille  Médaille Hôte     Nombred'épreuves(avec… Or                  \n 2 1924  médaillés tableau  Chamoni… 16                     16                  \n 3 1928  médaillés tableau  Saint-M… 14                     14                  \n 4 1932  médaillés tableau  Lake Pl… 14                     14                  \n 5 1936  médaillés tableau  Garmisc… 17                     17                  \n 6 1948  médaillés tableau  Saint-M… 22                     22                  \n 7 1952  médaillés tableau  Oslo, N… 22                     22                  \n 8 1956  médaillés tableau  Cortina… 24                     25                  \n 9 1960  médaillés tableau  Squaw V… 27                     28                  \n10 1964  médaillés tableau  Innsbru… 34                     34                  \n# ℹ 14 more rows\n# ℹ abbreviated name: ¹​`Nombred'épreuves(avec médailles)`\n# ℹ 5 more variables: `Médailles décernés` <chr>, `Médailles décernés` <chr>,\n#   `Médailles décernés` <chr>,\n#   `Athlète(s) avec le plus de médailles (Or-Argent-Bronze)` <chr>,\n#   `Athlète(s) avec le plus de médailles d'or` <chr>\n```\n:::\n:::\n\n\nCette commande nous a permis d'importer les données du site web wikipédia concernant les médailles olympiques. On a donc 6 tables avec des dimensions différentes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Création dataframe data_medailles_sport_ete\ndata_medailles_sport_ete = data.frame(list_tables[1])\n\n# Supression 1ère colonne et première ligne\ndata_medailles_sport_ete = data_medailles_sport_ete[,-1]\ndata_medailles_sport_ete = data_medailles_sport_ete[-1,]\n\n# Modification noms des colonnes\ncolnames(data_medailles_sport_ete) <- c(\"Discipline\", \"Annees\", \"Editions\",\n                                        \"Epreuves_2020\", \"Or\", \"Argent\", \"Bronze\", \"Total\", \"Athletes_medailles\",\n                                        \"Athletes_or\")\n\n# Transformation type de données\ndata_medailles_sport_ete[, 3:8] <- lapply(data_medailles_sport_ete[, 3:8], as.integer)\nstr(data_medailles_sport_ete)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t30 obs. of  10 variables:\n $ Discipline        : chr  \"Athlétisme\" \"Aviron\" \"Badminton\" \"Basket-ball\" ...\n $ Annees            : chr  \"Depuis 1896\" \"Depuis 1900\" \"Depuis 1992\" \"Depuis 1936\" ...\n $ Editions          : int  29 28 8 20 26 20 29 26 29 27 ...\n $ Epreuves_2020     : int  48 14 5 4 13 16 22 6 12 2 ...\n $ Or                : int  1028 269 39 32 266 242 263 151 223 34 ...\n $ Argent            : int  1030 268 39 32 266 241 261 149 223 34 ...\n $ Bronze            : int  1027 273 43 32 472 243 260 148 221 35 ...\n $ Total             : int  3085 810 121 96 1004 726 784 448 667 103 ...\n $ Athletes_medailles: chr  \"Paavo Nurmi (FIN) (9-3-0)\" \"Elisabeta Lipă (ROU) (5-2-1)\" \"Gao Ling (CHN) (2-1-1)\" \"Teresa Edwards (USA) (4-0-1)\" ...\n $ Athletes_or       : chr  \"Paavo Nurmi (FIN) (9-3-0) Carl Lewis (USA) (9-1-0)\" \"Elisabeta Lipă (ROU) (5-2-1) Georgeta Damian (ROU) (5-0-1) Steven Redgrave (GBR) (5-0-1)\" \"Gao Ling (CHN) (2-1-1) Kim Dong-moon (KOR) (2-0-1) Zhang Nan (CHN) (2-0-1) Ge Fei (CHN) (2-0-0) Gu Jun (CHN) (2\"| __truncated__ \"Teresa Edwards (USA) (4-0-1) Sue Bird (USA) (4-0-0) Tamika Catchings (USA) (4-0-0) Lisa Leslie (USA) (4-0-0) Di\"| __truncated__ ...\n```\n:::\n:::\n\n\nNous pouvons également noter que le jeu de données créé contient 30 observations et 10 variables et que les colonnes ont effectivement été renommées et pour certaines converties en colonnes d'entiers.\n\n## Les disciplines au cours du temps\n\nAvec ces données, nous pouvons en apprendre davantage sur les disciplines présentent lors des Jeux olympiques au cours du temps.\n\nTout d'abord, les trois disciplines avec le plus de médailles distribuées depuis le début des JO sont : L'Athlétisme avec 3085 médailles distribuées, la natation avec 1814 et la lutte avec 1358 médailles distribuées.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_medailles_sport_ete[order(-data_medailles_sport_ete$Total), c(1,8)][1:3,]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 Discipline Total\n2                Athlétisme  3085\n19 Natation(hommes, femmes)  1814\n18                    Lutte  1358\n```\n:::\n:::\n\n\nEnsuite, les trois disciplines ayant eu le moins d'épreuves en 2020 sont le Football, le Golf et le Handball avec 2 épreuves chacune.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_medailles_sport_ete[order(data_medailles_sport_ete$Epreuves_2020),c(1,4) ][1:3, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Discipline Epreuves_2020\n11   Football             2\n12       Golf             2\n14   Handball             2\n```\n:::\n:::\n\n\nCependant, ce ne sont pas les seules avec seulement 2 épreuves en 2020. En effet, ce sont celles-ci qui se sont affichées seulement en raison de l'ordre alphabatique mais il y a également le Hockey sur gazon, la natation synchronisée, le pentathlon moderne, le volley_ball et le water-polo :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubset(data_medailles_sport_ete, Epreuves_2020 == 2, select = c(Discipline, Epreuves_2020))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              Discipline Epreuves_2020\n11              Football             2\n12                  Golf             2\n14              Handball             2\n16      Hockey sur gazon             2\n20 Natation synchronisée             2\n21    Pentathlon moderne             2\n30           Volley-ball             2\n31            Water polo             2\n```\n:::\n:::\n\n\n## Calculer du nombre d'éditions\n\nNous proposons maintenant de créer une fonction nous permettant de calculer le nombre d'édition qu'il a eu pour chaque disciplines des JO. Avant de la créer nous allons suivre plusieurs étapes.\n\n### Création de la fonction calcul_nb_editions_int\n\nNous allons commencer par une fonction simple permettant de faire le calcul en fonction de la date de début renseignée. Cette fonction ne prendra alors qu'un paramètre correspondant à cette date qui est donc de type entier.\n\nCependant, avant de la créer, nous devons faire attention aux guerres mondiales qui influencent le nombre d'éditions. Ainsi, il est nécessaire de prendre en compte le fait qu'il n'y a pas eu d'édition des JO en 1916, 1940 et 1944. Donc notre fonction va devoir contenir des conditions telles que : - Si la date rentrée est inférieure ou égale à 1916 enlever 3, - Si la date renseignée est est supérieure à 1916 mais inférieure ou égale à 1940 enlever 2, - Si la date renseignée est supérieure à 1940 et inférieure ou égale à 1944 enlever 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalcul_nb_editions_int <- function(depuis) {\n  Edition_nombre <- (((2020 - depuis) / 4) + 1)\n  \n  if (depuis <= 1916) {\n    Edition_nombre <- Edition_nombre - 3\n  } else if (depuis <= 1940) {\n    Edition_nombre <- Edition_nombre - 2\n  } else if (depuis <= 1944) {\n    Edition_nombre <- Edition_nombre - 1\n  }\n  \n  return(Edition_nombre)\n} \n\ncalcul_nb_editions_int(1992)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8\n```\n:::\n:::\n\n\nGrâce à cette fonction, il est possible d'observer qu'une discipline qui a fait sa première apparition aux JO en 1992 par exemple a été présente lors de 8 éditions.\n\n### Création de la fonction calcul_nb_editions_str\n\nMaintenant on va essayer de créer une fonction prenant en argument des données de type caractères. Il est alors nécessaire d'identifier les différents patterns afin de les traiter correctement.\n\nGrâce à cette commande nous pouvons identifier les différents patterns:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_medailles_sport_ete$Annees\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Depuis 1896\"                      \"Depuis 1900\"                     \n [3] \"Depuis 1992\"                      \"Depuis 1936\"                     \n [5] \"1904, 1908,depuis 1920\"           \"Depuis 1936\"                     \n [7] \"Depuis 1896\"                      \"1900,depuis 1912\"                \n [9] \"Depuis 1896\"                      \"1900–1928,depuis 1936\"           \n[11] \"1900–1904,depuis 2016\"            \"Depuis 1896\"                     \n[13] \"1936,depuis 1972\"                 \"1896, 1904,depuis 1920\"          \n[15] \"1908, 1920,depuis 1928\"           \"1964,depuis 1972\"                \n[17] \"1896,depuis 1904\"                 \"Depuis 1896\"                     \n[19] \"Depuis 1984\"                      \"Depuis 1912\"                     \n[21] \"Depuis 1904\"                      \"Depuis 2000\"                     \n[23] \"1896–1924,depuis 1988\"            \"Depuis 1988\"                     \n[25] \"1896, 1900,1908–1924,depuis 1932\" \"1900-1912, 1920,depuis 1972\"     \n[27] \"Depuis 2000\"                      \"1900,depuis 1908\"                \n[29] \"Depuis 1964\"                      \"1900,depuis 1908\"                \n```\n:::\n:::\n\n\nIl y en a donc 3 : - \"1908-1924\" par exemple (motif : \"-\"), dans ce cas il faut faire (1924-1908)/4 - \"depuis 1976\" par exemple (motif : \"depuis\" ou \"Depuis\"), dans ce cas il faut faire (2020-1976)/4 - \"1896\" par exemple, dans ce cas il faut juste ajouter un au reste du calcul.\n\nDe plus, il faut également prendre en compte les guerres mondiales donc en 1916, 1940 et 1944 il n'y a pas eu de JO.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalcul_nb_editions_str <- function(patterns_str) {\n  motifs <- unlist(strsplit(patterns_str, \",\\\\s*\"))\n  nb_editions <- numeric(length(motifs))\n  \n  for (i in seq_along(motifs)) {\n    motif <- motifs[i]\n    \n    if (grepl(\"-\", motif)) {\n      annees <- as.numeric(unlist(strsplit(motif, \"-\")))\n      nb_editions[i] <- ((annees[2] - annees[1]) %/% 4) + 1\n      \n      if (1916 %in% seq(annees[1], annees[2], by = 4) && \n          1940 %in% seq(annees[1], annees[2], by = 4) &&\n          1944 %in% seq(annees[1], annees[2], by = 4)) {\n        nb_editions[i] <- nb_editions[i] - 3\n      } else if ((1916 %in% seq(annees[1], annees[2], by = 4) && 1940 %in% seq(annees[1], annees[2], by = 4)) ||\n                 (1940 %in% seq(annees[1], annees[2], by = 4) && 1944 %in% seq(annees[1], annees[2], by = 4))) {\n        nb_editions[i] <- nb_editions[i] - 2\n      } else if (1916 %in% seq(annees[1], annees[2], by = 4) || \n                 1940 %in% seq(annees[1], annees[2], by = 4) || \n                 1944 %in% seq(annees[1], annees[2], by = 4)) {\n        nb_editions[i] <- nb_editions[i] - 1\n      }\n      \n    } else if (grepl(\"(?i)depuis\", motif)) {\n      annee_debut <- as.numeric(gsub(\"\\\\D\", \"\", motif))\n      nb_editions[i] <- length(seq(annee_debut, 2020, by = 4))\n      \n      if (annee_debut <= 1916) {\n        nb_editions[i] <- nb_editions[i] - 3\n      } else if (annee_debut <= 1940) {\n        nb_editions[i] <- nb_editions[i] - 2\n      } else if (annee_debut <= 1944) {\n        nb_editions[i] <- nb_editions[i] - 1\n      }\n      \n    } else {\n      nb_editions[i] <- 1\n    }\n  }\n  \n  return(sum(nb_editions, na.rm = TRUE))\n}\n\ncalcul_nb_editions_str(\"1896, 1904, depuis 1920\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 26\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_medailles_sport_ete %>%\n  filter(Annees == \"1896, 1904,depuis 1920\") %>%\n  select(Discipline)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Discipline\n1 Haltérophilie\n```\n:::\n:::\n\n\nGrâce à cette fonction, nous pouvons alors calculer le nombre d'éditions qu'il y a eu pour la discipline Haltérophilie par exemple. Nous trouvons 26, ce qui correspond à la valeur présente dans le tableau de données :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_medailles_sport_ete %>%\n  filter(Discipline == \"Haltérophilie\") %>%\n  select(Editions)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Editions\n1       26\n```\n:::\n:::\n\n\n### Création de la fonction générique calcul_nb_editions\n\nFinalement nous allons créer une fonction générique permettant de calculer à la fois des données de type integer et des données de type caractère.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalcul_nb_editions <- function(x) {\n  if (is.numeric(x)) {\n    return(calcul_nb_editions_int(x))\n  } else if (is.character(x)) {\n    return(calcul_nb_editions_str(x))\n  } else {\n    stop(\"Erreur\")\n  }\n}\n\ncalcul_nb_editions(2000)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6\n```\n:::\n\n```{.r .cell-code}\n# renvoie 6\ncalcul_nb_editions(\"1904-1924, depuis 1948\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 24\n```\n:::\n\n```{.r .cell-code}\n# renvoie 24\n```\n:::\n\n\nIci nous pouvons voir que notre fonction permet de renvoyer 6 éditions pour les disciplines étant apparu en 2000 et renvoie 24 pour celle(s) ayant eu lieu entre 1904-1924 puis depuis 1948.\n\n## Calculer du nombre de médailles\n\nMaintenant que nous avons créé une fonction permettant de calculer le nombre d'éditions nous pouvons en créer une permettant de calculer le nombre de médailles. Pour se faire nous allons d'abord commencer par visualiser la colonne sur Athletes_medailles afin de voir à quoi elle ressemble.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(data_medailles_sport_ete$Athletes_medailles)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Paavo Nurmi (FIN) (9-3-0)\"                                                                                                                                                                                                                                                                              \n[2] \"Elisabeta Lipă (ROU) (5-2-1)\"                                                                                                                                                                                                                                                                           \n[3] \"Gao Ling (CHN) (2-1-1)\"                                                                                                                                                                                                                                                                                 \n[4] \"Teresa Edwards (USA) (4-0-1)\"                                                                                                                                                                                                                                                                           \n[5] \"László Papp (HUN) (3-0-0) Félix Savón (CUB) (3-0-0) Teófilo Stevenson (CUB) (3-0-0) Roniel Iglesias (CUB) (2-0-1) Boris Lagutin (URS) (2-0-1) Oleg Saitov (RUS) (2-0-1) Zou Shiming (CHN) (2-0-1) Roberto Cammarelle (ITA) (1-1-1) Zbigniew Pietrzykowski (POL) (0-1-2) Arnold Vanderlyde (NED) (0-0-3)\"\n[6] \"Birgit Fischer (GER) (8-4-0)\"                                                                                                                                                                                                                                                                           \n```\n:::\n:::\n\n\nLe but de la fonction est d'afficher le nombre de médailles reçues par chacun des athlètes sauf que dans une même cellule, plusieurs athlètes peuvent être mentionnés comme nous pouvons le voir ci-dessus. Ainsi, il faut créer une fonction qui permette de distinguer les différents athlètes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalcul_medailles_individuelles <- function(data) {\n  athletes <- unlist(str_split(data, \"\\\\)\\\\s\", simplify = TRUE))\n  resultats <- numeric(length(athletes))\n  \n  for (i in seq_along(athletes)) {\n    medailles <- str_extract_all(athletes[i], \"\\\\d+\")\n    \n    if (length(medailles[[1]]) > 0) {\n      chiffres <- as.integer(medailles[[1]])\n      resultats[i] <- sum(chiffres)\n    }\n  }\n  \n  return(resultats[resultats != 0])\n}\n\n# Exemple résultats \nx <- c(\"Paavo Nurmi (FIN) (9-3-0)\",\n  \"Elisabeta Lipă (ROU) (5-2-1)\",\n  \"Gao Ling (CHN) (2-1-1)\",\n  \"Teresa Edwards (USA) (4-0-1)\",\n  \"László Papp (HUN) (3-0-0) Félix Savón (CUB) (3-0-0) Teófilo Stevenson (CUB) (3-0-0) Roniel Iglesias (CUB) (2-0-1) Boris Lagutin (URS) (2-0-1) Oleg Saitov (RUS) (2-0-1) Zou Shiming (CHN) (2-0-1) Roberto Cammarelle (ITA) (1-1-1) Zbigniew Pietrzykowski (POL) (0-1-2) Arnold Vanderlyde (NED) (0-0-3)\"\n)\ncalcul_medailles_individuelles(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 12  8  4  5  3  3  3  3  3  3  3  3  3  3\n```\n:::\n:::\n\n\nComme nous pouvons le voir, Paavo Nurmi a reçu 12 médailles, Elisabeta Lipa en a reçu 8...\n\nMaintenant que nous avons déterminé une fonction permettant de calculer le nombre de médailles de chaque athlètes nous sommes désormais en mesure d'identifier les 3 athlètes ayant reçu le plus de médailles. Cependant, avant de faire cela, il faut appliquer notre fonction à toute la colonne Athletes_medailles afin de déterminer le nombre de médailles reçues par chacun des athlètes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresultats_medailles <- sapply(data_medailles_sport_ete$Athletes_medailles, calcul_medailles_individuelles)\nresultats_medailles\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$`Paavo Nurmi (FIN) (9-3-0)`\n[1] 12\n\n$`Elisabeta Lipă (ROU) (5-2-1)`\n[1] 8\n\n$`Gao Ling (CHN) (2-1-1)`\n[1] 4\n\n$`Teresa Edwards (USA) (4-0-1)`\n[1] 5\n\n$...\n [1] 3 3 3 3 3 3 3 3 3 3\n\n$`Birgit Fischer (GER) (8-4-0)`\n[1] 12\n\n$`Jason Kenny (GBR) (7-2-0)`\n[1] 9\n\n$`Isabell Werth (GER) (7-5-0)`\n[1] 12\n\n$`Edoardo Mangiarotti (ITA) (6-5-2)`\n[1] 13\n\n$`Christie Rampone (USA) (3-1-0)`\n[1] 4\n\n$`Chandler Egan (USA) (1-1-0) Lydia Ko (NZL) (0-1-1) Francis Newton (USA) (0-1-1)`\n[1] 2 2 2\n\n$`Larissa Latynina (URS) (9-5-4)`\n[1] 18\n\n$`Andreï Lavrov (RUS) (3-0-1) Oh Seong-ok (KOR) (1-2-1)`\n[1] 4 4\n\n$`Pýrros Dímas (GRE) (3-0-1) Ronny Weller (GER) (1-2-1) Nikolaj Pešalov (BUL, CRO) (1-1-2) Norbert Schemansky (USA) (1-1-2) Eko Yuli Irawan (INA) (0-2-2)`\n[1] 4 4 4 4 4\n\n$`Leslie Claudius (IND) (3-1-0) Udham Singh (IND) (3-1-0) Teun de Nooijer (NED) (2-2-0) Luciana Aymar (ARG) (0-2-2)`\n[1] 4 4 4 4\n\n$`Teddy Riner (FRA) (3-0-2) Ryōko Tani (JPN) (2-2-1)`\n[1] 5 5\n\n$`Wilfried Dietrich (RFA) (1-2-2)`\n[1] 5\n\n$`Michael Phelps (USA) (23-3-2)`\n[1] 28\n\n$`Svetlana Romashina (RUS) (7-0-0)`\n[1] 7\n\n$`Pavel Lednev (URS) (2-2-3)`\n[1] 7\n\n$`Dmitri Sautin (RUS) (2-2-4)`\n[1] 8\n\n$`Hwang Kyung-seon (KOR) (2-0-1) Steven López (USA) (2-0-1) Hadi Saei (IRI) (2-0-1) María Espinoza (MEX) (1-1-1)`\n[1] 3 3 3 3\n\n$`Venus Williams (USA) (4-1-0) Kitty McKane (GBR) (1-2-2)`\n[1] 5 5\n\n$`Ma Long (CHN) (5-0-0) Wang Nan (CHN) (4-1-0) Wang Hao (CHN) (2-3-0)`\n[1] 5 5 5\n\n$`Carl Osburn (USA) (5-4-2)`\n[1] 11\n\n$`Hubert Van Innis (BEL) (6-4-0)`\n[1] 10\n\n$`Jonathan Brownlee (GBR) (1-1-1)`\n[1] 3\n\n$`Ben Ainslie (GBR) (4-1-0) Robert Scheidt (BRA) (2-2-1) Torben Grael (BRA) (2-1-2)`\n[1] 5 5 5\n\n$`Ana Fernández (CUB) (3-0-1) Kerri Walsh (USA) (3-0-1) Inna Ryskal (URS) (2-2-0) Sérgio Dutra Santos (BRA) (2-2-0) Sergey Tetyukhin (RUS) (1-1-2)`\n[1] 4 4 4 4 4\n\n$`Dezső Gyarmati (HUN) (3-1-1)`\n[1] 5\n```\n:::\n:::\n\n\nMaintenant que nous avons fait ça nous pouvons alors déterminer les athlètes ayant reçu le plus de médailles, il s'agit de Michael Phelps avec 28 médailles suivi de Larissa Latynina avec 18 médailles et Edoardo Mangiarotti avec 16 médailles :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlist_df <- list()\n\nfor (i in seq_along(resultats_medailles)) {\n  matches <- str_match_all(data_medailles_sport_ete$Athletes_medailles[i], \"([^\\\\(]+)\\\\s*\\\\([^)]+\\\\)\\\\s*\\\\((\\\\d+)-(\\\\d+)-(\\\\d+)\\\\)\")\n  \n  df <- tibble(\n    Athlete = trimws(matches[[1]][, 1]),\n    Medailles = resultats_medailles[[i]]\n  )\n  \n  list_df[[i]] <- df\n}\n\nfinal_df <- do.call(rbind, list_df)\nfinal_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 62 × 2\n   Athlete                         Medailles\n   <chr>                               <dbl>\n 1 Paavo Nurmi (FIN) (9-3-0)              12\n 2 Elisabeta Lipă (ROU) (5-2-1)            8\n 3 Gao Ling (CHN) (2-1-1)                  4\n 4 Teresa Edwards (USA) (4-0-1)            5\n 5 László Papp (HUN) (3-0-0)               3\n 6 Félix Savón (CUB) (3-0-0)               3\n 7 Teófilo Stevenson (CUB) (3-0-0)         3\n 8 Roniel Iglesias (CUB) (2-0-1)           3\n 9 Boris Lagutin (URS) (2-0-1)             3\n10 Oleg Saitov (RUS) (2-0-1)               3\n# ℹ 52 more rows\n```\n:::\n\n```{.r .cell-code}\nhead(final_df[order(-final_df$Medailles), ],3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 2\n  Athlete                           Medailles\n  <chr>                                 <dbl>\n1 Michael Phelps (USA) (23-3-2)            28\n2 Larissa Latynina (URS) (9-5-4)           18\n3 Edoardo Mangiarotti (ITA) (6-5-2)        13\n```\n:::\n:::\n\n\n## Les nationalités les plus représentées\n\nIl pourrait maintenant être intéressant de connaître les 3 nationalités les plus représentées, pour toutes les épreuves, au classement du nombre de médailles d'or individuelles reccueillies.\n\nOn créé alors d'abord une fonction permettant d'extraire la nationalité puis on l'applique sur la colonne Athletes_or. Enfin, on agrége les résultats de manière à sommer toutes les lignes et à obtenir les 3 nations les plus représentées, et leur effectif :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextraire_nationalite_athlete <- function(athletes) {\n  nationalites <- regmatches(athletes, gregexpr(\"\\\\(([A-Z]{3})\\\\)\", athletes))[[1]]\n  return(table(nationalites))\n}\n\nextraire_nationalite_athlete(\"Paavo Nurmi (FIN) (9-3-0) Carl Lewis (USA) (9-1-0)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnationalites\n(FIN) (USA) \n    1     1 \n```\n:::\n\n```{.r .cell-code}\nresultats_nationalites <- lapply(data_medailles_sport_ete$Athletes_or, extraire_nationalite_athlete)\nresultats_nationalites\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[1]]\nnationalites\n(FIN) (USA) \n    1     1 \n\n[[2]]\nnationalites\n(GBR) (ROU) \n    1     2 \n\n[[3]]\nnationalites\n(CHN) (KOR) \n    8     1 \n\n[[4]]\nnationalites\n(USA) \n    5 \n\n[[5]]\nnationalites\n(CUB) (HUN) \n    2     1 \n\n[[6]]\nnationalites\n(GER) \n    1 \n\n[[7]]\nnationalites\n(GBR) \n    1 \n\n[[8]]\nnationalites\n(GER) \n    1 \n\n[[9]]\nnationalites\n(HUN) \n    1 \n\n[[10]]\nnationalites\n(USA) \n    4 \n\n[[11]]\n< table of extent 0 >\n\n[[12]]\nnationalites\n(URS) \n    1 \n\n[[13]]\nnationalites\n(RUS) \n    1 \n\n[[14]]\nnationalites\n(GRE) (TUR) \n    2     2 \n\n[[15]]\nnationalites\n(AUS) (IND) \n    1     7 \n\n[[16]]\nnationalites\n(FRA) (JPN) \n    1     1 \n\n[[17]]\nnationalites\n(CUB) (JPN) \n    1     1 \n\n[[18]]\nnationalites\n(USA) \n    1 \n\n[[19]]\nnationalites\n(RUS) \n    1 \n\n[[20]]\nnationalites\n(HUN) \n    1 \n\n[[21]]\nnationalites\n(CHN) \n    2 \n\n[[22]]\nnationalites\n(CHN) (GBR) (IRI) (KOR) (USA) \n    2     1     1     1     1 \n\n[[23]]\nnationalites\n(USA) \n    2 \n\n[[24]]\nnationalites\n(CHN) \n    1 \n\n[[25]]\nnationalites\n(NOR) (USA) \n    1     4 \n\n[[26]]\nnationalites\n(BEL) \n    1 \n\n[[27]]\nnationalites\n(GBR) \n    1 \n\n[[28]]\nnationalites\n(DEN) (GBR) \n    1     1 \n\n[[29]]\nnationalites\n(CUB) (USA) \n    5     2 \n\n[[30]]\nnationalites\n(HUN) \n    1 \n```\n:::\n\n```{.r .cell-code}\nlist_df_nationalites <- list()\n\nfor (i in seq_along(resultats_nationalites)) {\n  df_nationalites <- as.data.frame(resultats_nationalites[[i]])\n  \n  list_df_nationalites[[i]] <- df_nationalites\n}\n\ndf_nationalites <- do.call(rbind, list_df_nationalites)\n\ndf_nationalites |>\n  group_by(nationalites) |>\n  summarise(Total = sum(Freq)) |>\n  arrange(desc(Total)) |>\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 2\n  nationalites Total\n  <fct>        <int>\n1 (USA)           20\n2 (CHN)           13\n3 (CUB)            8\n```\n:::\n:::\n\n\nAinsi, au vu des résultats, nous pouvons constater que les 3 nationalités les plus représentées, pour toutes les épreuves, au classement du nombre de médailles d'or individuelles reccueillies sont les USA avec 20 médailles d'or, la Chine avec 13 et Cuba avec 8.\n\n## Concernant les JO d'hiver\n\nFinalement, nous pouvons réappliquer ces fonctions sur le jeu de données sur les JO d'hiver.\n\nOn commence par effectuer quelques modifications sur la base de données :\n\n\n::: {.cell}\n\n```{.r .cell-code}\njo_hiver = data.frame(list_tables[2])\njo_hiver = jo_hiver[,-1]\njo_hiver = jo_hiver[-1,]\ncolnames(jo_hiver) <- c(\"Discipline\", \"Annees\", \"Editions\",\n                                        \"Epreuves_2020\", \"Or\", \"Argent\", \"Bronze\", \"Total\", \"Athletes_medailles\",\n                                        \"Athletes_or\")\n```\n:::\n\n\nEnsuite on applique la fonction calcul_medailles_individuelles :\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calcul_medailles_individuelles\n\nresultats_medailles_hiver <- sapply(jo_hiver$Athletes_medailles, calcul_medailles_individuelles)\nresultats_medailles_hiver\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$`Ole Einar Bjørndalen (NOR) (8-4-1)`\n[1] 13\n\n$`Bogdan Musiol (RDA) (1-5-1)`\n[1] 7\n\n$`Felix Gottwald (AUT) (3-1-3)`\n[1] 7\n\n$`Anna Le Moine (SWE) (2-0-0) Cathrine Lindahl (SWE) (2-0-0) Eva Lund (SWE) (2-0-0) Anette Norberg (SWE) (2-0-0)\\n Kaitlyn Lawes (CAN) (2-0-0)\\n John Morris (CAN) (2-0-0)\\n Kevin Martin (CAN) (1-1-0) Torger Nergård (NOR) (1-1-0) Mirjam Ott (SUI) (0-2-0)`\n[1] 2 2 2 2 2 2 2 2 2\n\n$`Jayna Hefford (CAN) (4-1-0) Hayley Wickenheiser (CAN) (4-1-0)`\n[1] 5 5\n\n$`Armin Zöggeler (ITA) (2-1-3)`\n[1] 6\n\n$`Tessa Virtue (CAN) (3-2-0)\\n Scott Moir (CAN) (3-2-0)`\n[1] 5 5\n\n$`Ireen Wüst (NED) (5-5-1)`\n[1] 11\n\n$`/  Viktor Ahn (KOR / RUS) (6-0-2) Apolo Anton Ohno (USA) (2-2-4)\\n Arianna Fontana (ITA) (1-2-5)`\n[1] 8 8 8\n\n$`Matti Nykänen (FIN) (4-1-0)`\n[1] 5\n\n$`Elizabeth Yarnold (GBR) (2-0-0) Martins Dukurs (LAT) (0-2-0) John Heaton (USA) (0-2-0) Gregor Stähli (SUI) (0-0-2)`\n[1] 2 2 2 2\n\n$`Kari Traa (NOR) (1-1-1)`\n[1] 3\n\n$`Kjetil André Aamodt (NOR) (4-2-2)`\n[1] 8\n\n$`Marit Bjørgen (NOR) (8-4-3)`\n[1] 15\n\n$`Kelly Clark (USA) (1-0-2)\\n Shaun White (USA) (3-0-0)\\n Jamie Anderson (USA) (2-1-0)\\n Zan Kosir (SVN) (0-1-2)`\n[1] 3 3 3 3\n```\n:::\n\n```{.r .cell-code}\nresultats_medailles_hiver <- map(jo_hiver$Athletes_medailles, calcul_medailles_individuelles)\nresultats_medailles_hiver\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[1]]\n[1] 13\n\n[[2]]\n[1] 7\n\n[[3]]\n[1] 7\n\n[[4]]\n[1] 2 2 2 2 2 2 2 2 2\n\n[[5]]\n[1] 5 5\n\n[[6]]\n[1] 6\n\n[[7]]\n[1] 5 5\n\n[[8]]\n[1] 11\n\n[[9]]\n[1] 8 8 8\n\n[[10]]\n[1] 5\n\n[[11]]\n[1] 2 2 2 2\n\n[[12]]\n[1] 3\n\n[[13]]\n[1] 8\n\n[[14]]\n[1] 15\n\n[[15]]\n[1] 3 3 3 3\n```\n:::\n\n```{.r .cell-code}\nlist_df_hiver <- map(jo_hiver$Athletes_medailles, ~{\n  resultats <- calcul_medailles_individuelles(.x)\n  df <- tibble(\n    Athlete = .x,\n    Medailles = resultats\n  )\n  return(df)\n})\n\nfinal_df_hiver <- bind_rows(list_df_hiver)\nfinal_df_hiver |> \n  arrange(desc(Medailles)) |>\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 2\n  Athlete                            Medailles\n  <chr>                                  <dbl>\n1 Marit Bjørgen (NOR) (8-4-3)               15\n2 Ole Einar Bjørndalen (NOR) (8-4-1)        13\n3 Ireen Wüst (NED) (5-5-1)                  11\n```\n:::\n:::\n\n\nOn constate alors que les trois athlètes ayant reçu le plus de médailles individuelles pour les JO d'hiver sont Marit Bjorgen avec 15 médailles, Ole Einar Bjorndalen avec 13 médailles et Ireen Wust avec 11 médailles.\n\nApplication de la fonction extraire_nationalite_athlete :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresultats_nationalites_hiver <- lapply(jo_hiver$Athletes_or, extraire_nationalite_athlete)\nresultats_nationalites_hiver\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[1]]\nnationalites\n(NOR) \n    1 \n\n[[2]]\nnationalites\n(GER) \n    2 \n\n[[3]]\nnationalites\n(AUT) (FIN) (GER) (NOR) (RDA) \n    1     1     1     2     1 \n\n[[4]]\nnationalites\n(CAN) (SWE) \n    2     4 \n\n[[5]]\nnationalites\n(CAN) \n    3 \n\n[[6]]\nnationalites\n(GER) \n    3 \n\n[[7]]\nnationalites\n(CAN) (NOR) (SWE) (URS) \n    2     1     1     1 \n\n[[8]]\nnationalites\n(URS) \n    1 \n\n[[9]]\n< table of extent 0 >\n\n[[10]]\nnationalites\n(FIN) (SUI) \n    1     1 \n\n[[11]]\nnationalites\n(GBR) \n    1 \n\n[[12]]\nnationalites\n(CAN) (USA) \n    1     1 \n\n[[13]]\nnationalites\n(CRO) (NOR) \n    1     1 \n\n[[14]]\nnationalites\n(NOR) \n    2 \n\n[[15]]\nnationalites\n(USA) \n    1 \n```\n:::\n\n```{.r .cell-code}\nlist_df_nationalites_hiver <- list()\n\nfor (i in seq_along(resultats_nationalites_hiver)) {\n  df_nationalites_hiver <- as.data.frame(resultats_nationalites_hiver[[i]])\n  \n  list_df_nationalites_hiver[[i]] <- df_nationalites_hiver\n}\n\ndf_nationalites_hiver <- do.call(rbind, list_df_nationalites_hiver)\ndf_nationalites_hiver\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   nationalites Freq\n1         (NOR)    1\n2         (GER)    2\n3         (AUT)    1\n4         (FIN)    1\n5         (GER)    1\n6         (NOR)    2\n7         (RDA)    1\n8         (CAN)    2\n9         (SWE)    4\n10        (CAN)    3\n11        (GER)    3\n12        (CAN)    2\n13        (NOR)    1\n14        (SWE)    1\n15        (URS)    1\n16        (URS)    1\n17        (FIN)    1\n18        (SUI)    1\n19        (GBR)    1\n20        (CAN)    1\n21        (USA)    1\n22        (CRO)    1\n23        (NOR)    1\n24        (NOR)    2\n25        (USA)    1\n```\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\n\ndf_nationalites_hiver |>\n  group_by(nationalites) |>\n  summarise(Total = sum(Freq)) |>\n  arrange(desc(Total)) |>\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 2\n  nationalites Total\n  <fct>        <int>\n1 (CAN)            8\n2 (NOR)            7\n3 (GER)            6\n```\n:::\n:::\n\n\nEt grâce à cette fonction, on peut constater que les 3 nationalités les plus représentées, pour toutes les épreuves, au classement du nombre de médailles d'or individuelles reccueillies sont le Canada avec 8 médailles d'or, la Norvège avec 7 et l'Allemagne avec 6.\n\n![Image libre de droit](grece.jpg)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}